sudo: false
language: node_js
node_js: "stable"
after_success:
- npm run deploy
env:
  global:
    secure: bbt0H64kLBu7nQfPmryfVBwruVzzpeDbmQ7bRtCqwCkwdmHVdZyyzzaTSv0c8pSGHUdoXIVHUfW1Drrtuaz5uNCIGIze6OTEKIV4EEkfXsMVdksTJ2DRBxCE78Anmj90wp4sPuGPIR7xLkhXC0y9/wtal0s6yW7x7O1QdxjS6vinwPTqUS7yE+nFSuYtAEoHSdx3tfFEbL+23kqLn66sQb1e2hM2YweR/0xZ/F+raOmVZbJcIqIlu0gLx7OXQCCbOCJ4wYAhDJDJCJEvpATjiAFLh7LJfXBeDJEHGAfKw0aOM1Qk2UnyBF3OeNszbexAKy5rS68HUFqCWRrUMZWoWAMCI+sPUK6t+NDjmCxwsnycQcMODDM8ZG++1yWIat9vfYRVk7XVmknABs4USH+5zv+vikPfBRp1C+yzEGh9t1cOgQPoMu0Frmoni819zRZGuTdAwwg02JpgWBbaKq+HQYpYZSrGLNqCTX6kFS4Yh+DO0vcL76T1r00QkbmxzmTvTCgcBoykkk8R1fP0przZedUIEzZsUF5j8AiZ6BCsjS7si4eX7JcXbB5mm45H5k9qMIjUzlCEyAmhuXlMhTRMYrOwz5q28R0BWug50yY6hCJkz07+hhF8PQUX3JWwMksj3yfjrMdCExHdvEapYf6kqVOs7rodzMlglI5iW51GrTc=
